version: '3'

services:
  postgres_container:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
    restart: always
  web:
    build:
      context: ./
    ports:
      - "8080:8080"
    restart: always



