version: '3'

services:
  agency_offers_database:
    image: postgres
    container_name: agency_offers_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: agency_offers_database
    volumes:
      - /var/lib/postgresql/data
    restart: always
    networks:
      - aman_network
  agency_management:
    build:
      context: ./agency
    ports:
      - "50001:50001"
    restart: always
    depends_on:
      - agency_offers_database
    environment:
      DB_HOST: agency_offers_database
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: agency_offers_database
      DB_PORT: 5432
    networks:
      - aman_network
  offer_management:
    build:
      context: ./offer
    ports:
      - "50002:50002"
    restart: always
    depends_on:
      - agency_offers_database
    environment:
      DB_HOST: agency_offers_database
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: agency_offers_database
      DB_PORT: 5432
    networks:
      - aman_network


networks:
  aman_network:
    driver: bridge
    external: true
